import {Application} from './application';

export const APPLICATIONS: Array<Application> = [
    {
        createDate: '',
        dependency: [],
        description: '',
        downloadSize: '100 MB',
        icon: '',
        id: '1',
        like: 0,
        message: 'Installing Chocolately',
        name: 'Chocolately',
        passive: false,
        publisher: '',
        quiet: false,
        quitCode: 0,
        restart: true,
        script: 'iex (new-object net.webclient).DownloadString("https://chocolatey.org/install.ps1")',
        sourceURL: '',
        supportedOS: [{name: 'Windows 8 x64'}, {name: 'Windows 10 x64'}],
        version: ''
    },
    {
        createDate: '',
        dependency: [],
        description: '',
        downloadSize: '100 MB',
        icon: '',
        id: '2',
        like: 0,
        message: 'Installing Web Platform Installer Command Line',
        name: 'Web Platform Installer Command Line',
        passive: false,
        publisher: '',
        quiet: false,
        quitCode: 0,
        restart: true,
        script: 'cinst webpicmd --force --yes',
        sourceURL: '',
        supportedOS: [{name: 'Windows 8 x64'}, {name: 'Windows 10 x64'}],
        version: ''
    },
    {
        createDate: '',
        dependency: [],
        description: '',
        downloadSize: '100 MB',
        icon: 'https://chocolatey.org/content/packageimages/nodejs.install.7.3.0.png',
        id: '3',
        like: 0,
        message: 'Installing Node JS',
        name: 'Node JS',
        passive: false,
        publisher: '',
        quiet: false,
        quitCode: 0,
        restart: true,
        script: 'cinst nodejs.install --force --yes',
        sourceURL: '',
        supportedOS: [{name: 'Windows 8 x64'}, {name: 'Windows 10 x64'}],
        version: ''
    },
    {
        createDate: '',
        dependency: [],
        description: '',
        downloadSize: '100 MB',
        icon: '',
        id: '4',
        like: 0,
        message: 'Installing Visual Studio',
        name: 'Visual Studio',
        passive: false,
        publisher: '',
        quiet: false,
        quitCode: 0,
        restart: true,
        script: 'iex (new-object net.webclient).DownloadString("https://raw.githubusercontent.com/ahwhfei/DevEnvironmentInstallation/develop/plugins/visualstudio/Install-VisualStudio.ps1")',
        sourceURL: '',
        supportedOS: [{name: 'Windows 8 x64'}, {name: 'Windows 10 x64'}],
        version: ''
    },
    {
        createDate: '',
        dependency: [],
        description: '',
        downloadSize: '100 MB',
        icon: 'https://chocolatey.org/content/packageimages/GoogleChrome.55.0.2883.87.svg',
        id: '5',
        like: 0,
        message: 'Installing Google Chrome',
        name: 'Google Chrome',
        passive: false,
        publisher: '',
        quiet: false,
        quitCode: 0,
        restart: true,
        script: 'cinst googlechrome --force --yes',
        sourceURL: '',
        supportedOS: [{name: 'Windows 8 x64'}, {name: 'Windows 10 x64'}],
        version: ''
    },
    {
        createDate: '',
        dependency: [],
        description: '',
        downloadSize: '100 MB',
        icon: '',
        id: '6',
        like: 0,
        message: 'Installing Sublime Text3',
        name: 'Sublime Text3',
        passive: false,
        publisher: '',
        quiet: false,
        quitCode: 0,
        restart: true,
        script: 'cinst sublimetext3 --force --yes',
        sourceURL: '',
        supportedOS: [{name: 'Windows 8 x64'}, {name: 'Windows 10 x64'}],
        version: ''
    },
    {
        createDate: '',
        dependency: [],
        description: '',
        downloadSize: '100 MB',
        icon: '',
        id: '7',
        like: 0,
        message: 'Installing Visual Studio Code',
        name: 'Visual Studio Code',
        passive: false,
        publisher: '',
        quiet: false,
        quitCode: 0,
        restart: true,
        script: 'cinst visualstudiocode --force --yes',
        sourceURL: '',
        supportedOS: [{name: 'Windows 8 x64'}, {name: 'Windows 10 x64'}],
        version: ''
    },
    {
        createDate: '',
        dependency: [],
        description: '',
        downloadSize: '100 MB',
        icon: '',
        id: '8',
        like: 0,
        message: 'Installing Source Tree',
        name: 'Source Tree',
        passive: false,
        publisher: '',
        quiet: false,
        quitCode: 0,
        restart: true,
        script: 'cinst sourcetree --force --yes',
        sourceURL: '',
        supportedOS: [{name: 'Windows 8 x64'}, {name: 'Windows 10 x64'}],
        version: ''
    },
    {
        createDate: '',
        dependency: [],
        description: '',
        downloadSize: '100 MB',
        icon: '',
        id: '9',
        like: 0,
        message: 'Installing Git',
        name: 'Git',
        passive: false,
        publisher: '',
        quiet: false,
        quitCode: 0,
        restart: true,
        script: 'cinst git --force --yes',
        sourceURL: '',
        supportedOS: [{name: 'Windows 8 x64'}, {name: 'Windows 10 x64'}],
        version: ''
    },
    {
        createDate: '',
        dependency: [],
        description: '',
        downloadSize: '100 MB',
        icon: '',
        id: '10',
        like: 0,
        message: 'Installing ReSharper',
        name: 'ReSharper',
        passive: false,
        publisher: '',
        quiet: false,
        quitCode: 0,
        restart: true,
        script: 'cinst resharper --force --yes',
        sourceURL: '',
        supportedOS: [{name: 'Windows 8 x64'}, {name: 'Windows 10 x64'}],
        version: ''
    },
    {
        createDate: '',
        dependency: [],
        'description': '',
        downloadSize: '100 MB',
        icon: '',
        id: '11',
        like: 0,
        message: 'Installing Java Runtime Environment',
        name: 'JRE',
        passive: false,
        publisher: '',
        quiet: false,
        quitCode: 0,
        restart: true,
        script: 'cinst jre8 --force --yes',
        sourceURL: '',
        supportedOS: [{name: 'Windows 8 x64'}, {name: 'Windows 10 x64'}],
        version: ''
    },
    {
        createDate: '',
        dependency: [],
        description: '',
        downloadSize: '100 MB',
        icon: '',
        id: '12',
        like: 0,
        message: 'Installing Wix Toolset',
        name: 'Wix Toolset',
        passive: false,
        publisher: '',
        quiet: false,
        quitCode: 0,
        restart: true,
        script: 'cinst wixtoolset --force --yes --allow-empty-checksums',
        sourceURL: '',
        supportedOS: [{name: 'Windows 8 x64'}, {name: 'Windows 10 x64'}],
        version: ''
    },
    {
        createDate: '',
        dependency: [],
        description: '',
        downloadSize: '100 MB',
        icon: '',
        id: '13',
        like: 0,
        message: 'Installing Azure PowerShell',
        name: 'Azure PowerShell',
        passive: false,
        publisher: '',
        quiet: false,
        quitCode: 0,
        restart: true,
        script: 'webpicmd /install /products:"Microsoft Azure PowerShell" /AcceptEULA /SuppressReboot',
        sourceURL: '',
        supportedOS: [{name: 'Windows 8 x64'}, {name: 'Windows 10 x64'}],
        version: ''
    },
    {
        createDate: '',
        dependency: [],
        description: '',
        downloadSize: '100 MB',
        icon: '',
        id: '14',
        like: 0,
        message: 'Installing Azure SDK',
        name: 'Azure SDK for .net (VS2015) - 2.9.6',
        passive: false,
        publisher: '',
        quiet: false,
        quitCode: 0,
        restart: true,
        script: 'webpicmd /install /products:"Microsoft Azure SDK for .NET (VS 2015) - 2.9.6"',
        sourceURL: '',
        supportedOS: [{name: 'Windows 8 x64'}, {name: 'Windows 10 x64'}],
        version: ''
    },
    {
        createDate: '',
        dependency: [],
        description: '',
        downloadSize: '100 MB',
        icon: '',
        id: '15',
        like: 0,
        message: 'Installing Azure Service Fabric SDK',
        name: 'Azure Service Fabric SDK',
        passive: false,
        publisher: '',
        quiet: false,
        quitCode: 0,
        restart: true,
        script: 'webpicmd /install /products:"Microsoft Azure Service Fabric SDK and Tools - 2.4.145 (VS2015)" /AcceptEULA /SuppressReboot',
        sourceURL: '',
        supportedOS: [{name: 'Windows 8 x64'}, {name: 'Windows 10 x64'}],
        version: ''
    },
    {
        createDate: '',
        dependency: [],
        description: '',
        downloadSize: '100 MB',
        icon: '',
        id: '16',
        like: 0,
        message: 'Installing Aws SDK',
        name: 'Aws SDK',
        passive: false,
        publisher: '',
        quiet: false,
        quitCode: 0,
        restart: true,
        script: 'Start-Process -FilePath msiexec.exe -ArgumentList "/i https://sdk-for-net.amazonwebservices.com/latest/AWSToolsAndSDKForNet.msi /quiet /norestart" -wait',
        sourceURL: '',
        supportedOS: [{name: 'Windows 8 x64'}, {name: 'Windows 10 x64'}],
        version: ''
    }
];
